image: alpine/latest
sources:
  - https://git.sr.ht/~mna/mna.dev
tasks:
  - build: |
      cd mna.dev
      git remote add mirror git@github.com:mna/mna.dev.git
      git push mirror master
secrets:
  - 8a632639-cb32-49f8-b6b8-8040972f80a7
  - b771aa79-c02a-4f92-b9ef-bc387bfa5647

